version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app

  db:
    image: mysql:8
    restart: always
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    ports:
      - "${DB_PORT_EXPOSE}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    networks:
      - app

networks:
  app:

volumes:
  db-config:
  db-data:
  node_modules:
