version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2000:2000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
